### PR TITLE
Sensitive: Test on chef 12. Minor fix for the sensitive attribute

### LINKED ISSUE #110: 2.0.0 Issue with delete_lines - sensitive
### Cookbook version
2.0.0

### Chef-client version
12.21.14

### Platform Details
RHEL

### Scenario:
Trying to use delete_lines resource

### Steps to Reproduce:
Use delete_lines resource

### Expected Result:
Lines deleted from file

### Actual Result:
```
 ================================================================================
           Error executing action `edit` on resource 'delete_lines[Remove mware from sudoers]'
           ================================================================================

           ArgumentError
           -------------
           Property sensitive is not defined in class delete_lines[Remove mware from sudoers]

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/line/libraries/helper.rb:13:in `sensitive_default'
           /tmp/kitchen/cache/cookbooks/line/resources/delete_lines.rb:12:in `block in class_from_file'
```
Looks like you need to add 'properties' to the resource

### PR DESCRIPTION
**Pull request by MarkGibbons**
### Description

Test and run the cookbook on chef 12

### Issues Resolved

#110

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/111)

### CODE REVIEW

File: libraries/helper.rb [hunk 1]
```diff
@@ -11,6 +11,9 @@ def raise_not_found
 
     def sensitive_default
       new_resource.sensitive = true unless property_is_set?(:sensitive)
```
Comment (damacus) [inline libraries/helper.rb:13]: I think this can be 
```ruby
val = new_resource.sensitive ? new_resource.sensitive : true
```
This looks like it's always going to set sensitive as true in Chef 12

Comment (MarkGibbons) [reply libraries/helper.rb:13]: Setting sensitive to true for chef 12 seemed like my best option.  With Chef 13 and up folks can specify the sensitive property and it works correctly.  

For chef 12 new_resource.sensitive defaults to false instead of nil.  So I can't tell if it has been set and property_is_set?(:sensitive) throws an ArgumentError. The line resources used to always act like sensitive was true before we used the internal file resource so I'm trying go back to that behavior just for chef 12.  Instead of using
````new_resource.sensitive = true```` for chef 12 I could just leave new_resource.sensitive alone.  But then the default behavior changes when run on chef 12 compared to chef 13.

Isn't "val" in the code above is always going to be truthy?

thanks,
   Mark

**Comment by damacus** [comment]
Ah good point, it's a sensible default.

Go with it!

**Comment by MarkGibbons** [comment]
@damacus Could you hit the approval button on a review?
Thanks,
   Mark

**Review by damacus — APPROVED** [review]
