### PR TITLE
Append trailing newline

### LINKED ISSUE #113: Line added repeatedly
### Cookbook version
2

### Chef-client version
Any

### Platform Details
Ubuntu, Windows

### Scenario:
Append a line (also replace a line). Try to do it once.  With the right pattern the line is inserted repeatedly.  Newlines in the append line pattern won't work.  Line does not support  appending multiple lines.

### Steps to Reproduce:
Specify append_if_no_line where the line is:
"text\n"

append_if_no_line file do
  line "text\n"
end

### Expected Result:
Insert the line once or blow up.

### Actual Result:
The line is appended with every execution of the resource.

### PR DESCRIPTION
**Pull request by MarkGibbons**
### Description

The nfs cookbook adds lines with trailing blanks.  Append will never match the existing line and will allows append. One of the worst things we can do is add the same line over and over.  This change chomps the input line so that the comparisons work.  The change also checks for other embedded end of line (EOL) characters and raises an error if they are found.  Embedded characters will also cause repeated appends.  Support for Windows made adding lines with EOL characters impossible.

### Issues Resolved

#113

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/line-cookbook/114)

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by damacus — COMMENTED** [review]
Rather than making an openstruct you could go with a double instead.

But you have to fill out the full resource with a double. Thoughts?

**Comment by MarkGibbons** [comment]
thanks. I've never quite written a test that way. Hope this is what you had in mind.

**Comment by damacus** [comment]
This is what I'm doing in postgresql, I'm not sure whether it's any better but it certainly works! 

https://github.com/sous-chefs/postgresql/blob/master/spec/libraries/helpers_spec.rb#L172-L191

**Comment by MarkGibbons** [comment]
That example works in postgresql because you are passing new_resource as an argument to the helper module.  I'm not.  So I need to trap the execution of the new_resource method and supply the double. Other than how we invoke new resource the two test methods are the same I think.

My helpers will never be used outside of the line cookbook resources so I skipped passing new_resource.  You could do that in postgrsql and simplify the calling signature for the methods.
I don't think any of these calls like "user_has_password?(new_resource)" actually need new_resource as an argument. new_resource is a method and should already be in scope for the Helper mixin.

Using the double is a lot simpler.  I like it.  Thanks

**Comment by damacus** [comment]
That's a good point. I got into a habit of doing it because it fixed it
once.

**Comment by MarkGibbons** [comment]
That's the same reason I had the ostruct construct in there.  It worked once.  :)

File: resources/replace_or_add.rb [hunk 1]
```diff
@@ -20,15 +21,15 @@
   # replace
   current.each do |line|
     line = line.dup
-    if line =~ regex || line == new_resource.line
+    if line =~ regex || line == add_line
       found = true
-      line = new_resource.line unless line == new_resource.line
+      line = add_line unless line == add_line
```
Comment (josephholsten) [inline resources/replace_or_add.rb]: I'm confused why the conditional in this line was needed in the first place and is needed now. What's wrong with a mere:

```rb
line = add_line
```

File: libraries/helper.rb [hunk 2]
```diff
@@ -1,5 +1,11 @@
 module Line
   module Helper
+    def embedded_eol(line)
```
Comment (josephholsten) [inline libraries/helper.rb]: maybe name this `embedded_eol_guard()` or `validate_no_eol()`? I feel like a function `embedded_eol(string) -> string` would add an EOL to the end of the string, or otherwise /add/ EOL to the string, which obviously isn't what's happening.

**Review by josephholsten — DISMISSED** [review]
I added some pedantic critiques, but I don't see anything actually wrong with the patch. LGTM!

**Comment by MarkGibbons** [comment]
I think I'll use chomp_eol for the method name instead of embedded_eol.  It will raise an error if it can't remove all of them.
I'll nuke the extra check for the line replacement.  It was left over from about 4 releases back.
thanks for looking.

**Review by atomic-penguin — APPROVED** [review]
